install:
  - rm -rf public || exit 0

before_script:
  - ssh -T git@github.com
  - ssh -T git@github.com > ssh_output.txt 2>&1
  - git submodule update --init --recursive --verbose

# Build the website
script:
  - binary/hugo --theme=even
  # - echo 'juneyuan.github.io/blog' > public/CNAME
# Deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master
