install:
  - rm -rf public || exit 0
# Build the website
script:
  - binary/hugo --theme=even
  # - echo 'juneyuan.github.io/blog' > public/CNAME
# Deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master
