baseURL = "https://juneyuan.github.io"
languageCode = "zh-cn"
defaultContentLanguage = "en"                             # en / zh-cn / ... (This field determines which i18n file to use)
title = "June Yuan's Blog"
theme = "github-style"
pygmentsCodeFences = true
pygmentsUseClasses = true
enableRobotsTXT = true
enableEmoji = true

preserveTaxonomyNames = true
hasCJKLanguage = true     # has chinese/japanese/korean ? # 自动检测是否包含 中文\日文\韩文
# paginate = 5                                              # 首页每页显示的文章数
# disqusShortname = ""      # disqus_shortname
# googleAnalytics = ""      # UA-XXXXXXXX-X
# copyright = ""            # default: author.name ↓        # 默认为下面配置的author.name ↓

[params]
  author = "JuneYuan"
  description = "."
  github = "JuneYuan"
  email = "smartjune@qq.com"
  favicon = "/images/github.png"
  avatar = "/images/avatar.jpeg"
  headerIcon = "/images/github.png"
  location = "China"
  enableGitalk = true



